import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/')({
  component: HomePage,
})

function HomePage() {
  return (
    <main style={{ fontFamily: 'system-ui, sans-serif', padding: '2rem', maxWidth: 720 }}>
      <p style={{ letterSpacing: '0.12em', textTransform: 'uppercase', opacity: 0.7 }}>
        Generated by Arche
      </p>
      <h1>TanStack Start is ready.</h1>
      <p>
        File-based routes, SSR, and server routes. Probe <code>/api/health</code> after{' '}
        <code>bun run dev</code>.
      </p>
    </main>
  )
}
