'use client'

import { useQuery } from '@tanstack/react-query'
import { useTRPC } from '@/trpc/client'

const services = [
  ['Web', 'Next.js app router', 'http://localhost:3000'],
  ['API', 'Express + tRPC', 'http://localhost:3001/health'],
  ['Database', 'Prisma-owned schema', 'packages/store'],
  ['Auth', 'Better Auth boundary', 'packages/auth'],
] as const

function TrpcStatus() {
  const trpc = useTRPC()
  const hello = useQuery(trpc.hello.queryOptions({ name: 'Arche' }))

  const status = hello.isPending ? 'checking' : hello.isError ? 'offline' : 'online'
  const message = hello.isPending
    ? 'Checking tRPC contract...'
    : hello.isError
      ? hello.error.message
      : hello.data

  return (
    <section className="status" aria-label="Live API status">
      <div>
        <span className={status === 'online' ? 'dot online' : 'dot'} />
        <p className="eyebrow">Live tRPC check</p>
        <h2>{message}</h2>
      </div>
      <code>NEXT_PUBLIC_API_URL=http://localhost:3001</code>
    </section>
  )
}

export default function HomePage() {
  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">Generated by Arche</p>
        <h1>Your fullstack base is ready.</h1>
        <p className="lede">
          This scaffold starts with a Next.js web app, an Express API, tRPC contracts, Better Auth,
          Prisma, and production-minded Docker and CI files that match this route.
        </p>
        <div className="actions" aria-label="Local commands">
          <code>bun dev</code>
          <code>bun run db:migrate</code>
        </div>
      </section>

      <TrpcStatus />

      <section className="grid" aria-label="Generated services">
        {services.map(([name, detail, target]) => (
          <article key={name} className="card">
            <span>{name}</span>
            <h2>{detail}</h2>
            <p>{target}</p>
          </article>
        ))}
      </section>
    </main>
  )
}
