import type { Metadata } from 'next'
import Link from 'next/link'
import { helloQueryOptions, HydrateClient, prefetch } from '@/trpc/server'
import { TrpcStatus } from './trpc-status'

export const metadata: Metadata = {
  title: 'Arche Scaffold',
  description: 'Fullstack scaffold homepage with live tRPC status.',
}

const services = [
  ['Web', 'Next.js app router', 'http://localhost:3000'],
  ['API', 'Express + tRPC', 'http://localhost:3001/health'],
  ['Database', 'Prisma-owned schema', 'packages/store'],
  ['Auth', 'Better Auth boundary', 'packages/auth'],
] as const

export default async function HomePage() {
  await prefetch(helloQueryOptions('Arche'))

  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">Generated by Arche</p>
        <h1>Your fullstack base is ready.</h1>
        <p className="lede">
          This scaffold starts with a Next.js web app, an Express API, tRPC contracts, Better Auth,
          Prisma, and production-minded Docker and CI files that match this route.
        </p>
        <div className="actions" aria-label="Local commands">
          <code>bun dev</code>
          <code>bun run db:migrate</code>
          <Link href="/live" className="live-link-button">
            Open live proof run →
          </Link>
        </div>
      </section>

      <HydrateClient>
        <TrpcStatus />
      </HydrateClient>

      <section className="grid" aria-label="Generated services">
        {services.map(([name, detail, target]) => (
          <article key={name} className="card">
            <span>{name}</span>
            <h2>{detail}</h2>
            <p>{target}</p>
          </article>
        ))}
      </section>
    </main>
  )
}
