'use client'

import { useEffect, useState } from 'react'
import { queryHello } from '@/trpc/client'

const services = [
  ['Web', 'Next.js app router', 'http://localhost:3000'],
  ['API', 'Express + tRPC', 'http://localhost:3001/health'],
  ['Database', 'Prisma-owned schema', 'packages/store'],
  ['Auth', 'Better Auth boundary', 'packages/auth'],
] as const

type ApiState =
  | { status: 'checking'; message: string }
  | { status: 'online'; message: string }
  | { status: 'offline'; message: string }

function TrpcStatus() {
  const [apiState, setApiState] = useState<ApiState>({
    status: 'checking',
    message: 'Checking tRPC contract...',
  })

  useEffect(() => {
    let cancelled = false

    queryHello('Arche')
      .then((message) => {
        if (!cancelled) setApiState({ status: 'online', message })
      })
      .catch((error: unknown) => {
        if (cancelled) return
        setApiState({
          status: 'offline',
          message: error instanceof Error ? error.message : 'API is not reachable yet',
        })
      })

    return () => {
      cancelled = true
    }
  }, [])

  return (
    <section className="status" aria-label="Live API status">
      <div>
        <span className={apiState.status === 'online' ? 'dot online' : 'dot'} />
        <p className="eyebrow">Live tRPC check</p>
        <h2>{apiState.message}</h2>
      </div>
      <code>NEXT_PUBLIC_API_URL=http://localhost:3001</code>
    </section>
  )
}

export default function HomePage() {
  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">Generated by Arche</p>
        <h1>Your fullstack base is ready.</h1>
        <p className="lede">
          This scaffold starts with a Next.js web app, an Express API, tRPC contracts, Better Auth,
          Prisma, and production-minded Docker and CI files that match this route.
        </p>
        <div className="actions" aria-label="Local commands">
          <code>bun dev</code>
          <code>bun run db:migrate</code>
        </div>
      </section>

      <TrpcStatus />

      <section className="grid" aria-label="Generated services">
        {services.map(([name, detail, target]) => (
          <article key={name} className="card">
            <span>{name}</span>
            <h2>{detail}</h2>
            <p>{target}</p>
          </article>
        ))}
      </section>
    </main>
  )
}
