import type { Metadata } from 'next'

import { Providers } from './providers'
import './styles.css'

export const metadata: Metadata = {
  title: 'Arche Scaffold',
  description: 'Next.js + Convex scaffold generated by Arche',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
