'use client'

import { useQuery } from 'convex/react'
import { api } from '../convex/_generated/api'

const services = [
  ['Web', 'Next.js App Router'],
  ['Backend', 'Convex functions + schema'],
  ['Auth', 'Better Auth stubs when enabled'],
] as const

export default function HomePage() {
  const posts = useQuery(api.posts.listPublished)

  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">Generated by Arche</p>
        <h1>Your Convex product base is ready.</h1>
        <p className="lede">
          Real-time data without wiring Express or Prisma. Run <code>bun run dev</code> to start
          Convex and Next.js together—published posts from your schema appear below.
        </p>
        <div className="actions" aria-label="Local commands">
          <code>bun run dev</code>
          <code>bunx convex dev</code>
        </div>
      </section>

      <section className="posts" aria-label="Published posts">
        <p className="eyebrow">Live data</p>
        <h2>Published posts</h2>
        {posts === undefined ? (
          <p className="muted">Loading from Convex…</p>
        ) : posts.length === 0 ? (
          <p className="muted">
            No published posts yet. Add one in the Convex dashboard or seed script.
          </p>
        ) : (
          <ul className="post-list">
            {posts.map((post) => (
              <li key={post._id}>{post.title}</li>
            ))}
          </ul>
        )}
      </section>

      <section className="grid" aria-label="Generated services">
        {services.map(([name, detail]) => (
          <article key={name} className="card">
            <span>{name}</span>
            <h2>{detail}</h2>
          </article>
        ))}
      </section>
    </main>
  )
}
