/** Premium minimalist homepage for service-API fullstack scaffolds (rust-fullstack, polyglot swaps). */

export function renderServiceApiWebQueryClient(): string {
  return `import { QueryClient } from '@tanstack/react-query'

export function makeQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: {
        staleTime: 30 * 1000,
      },
    },
  })
}
`
}

export function renderServiceApiWebProviders(): string {
  return `'use client'

import { QueryClientProvider } from '@tanstack/react-query'
import { useState } from 'react'
import { makeQueryClient } from '@/trpc/query-client'

export function Providers({ children }: { children: React.ReactNode }) {
  const [queryClient] = useState(() => makeQueryClient())
  return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
}
`
}

export function renderServiceApiWebLayout(): string {
  return `import type { Metadata } from 'next'
import { Providers } from './providers'
import './styles.css'

export const metadata: Metadata = {
  title: 'Arche Scaffold',
  description: 'Service-backed fullstack scaffold generated by Arche.',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
`
}

export function renderServiceApiWebPage(): string {
  return `'use client'

import { useQuery } from '@tanstack/react-query'

const services = [
  ['Web', 'Next.js app router', 'http://localhost:3000'],
  ['API', 'Axum REST + SQLx', 'http://localhost:3001'],
  ['Posts', 'Module-first CRUD', '/posts'],
  ['Runtime', 'Service-owned backend', 'services/api'],
] as const

type PostPreview = { id: string; title: string }

function apiBase(): string {
  return (process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001').replace(/\\/$/, '')
}

function ApiStatus() {
  const { data, isPending, isError, error } = useQuery({
    queryKey: ['health'],
    queryFn: async ({ signal }) => {
      const response = await fetch(\`\${apiBase()}/health\`, {
        signal,
        headers: { accept: 'application/json' },
      })
      if (!response.ok) throw new Error(\`HTTP \${response.status}\`)
      const payload = (await response.json().catch(() => null)) as { status?: string } | null
      return payload?.status ? \`API says \${payload.status}\` : 'API health route is online'
    },
  })

  const status = isPending ? 'checking' : isError ? 'offline' : 'online'
  const message = isPending
    ? 'Checking API health...'
    : isError
      ? error instanceof Error
        ? error.message
        : 'API is not reachable yet'
      : data

  return (
    <section className="status" aria-label="Live API status">
      <div>
        <span className={status === 'online' ? 'dot online' : 'dot'} />
        <p className="eyebrow">Live API check</p>
        <h2>{message}</h2>
      </div>
      <code>NEXT_PUBLIC_API_URL=http://localhost:3001</code>
    </section>
  )
}

function PostsPreview() {
  const { data, isPending, isError, error } = useQuery({
    queryKey: ['posts', { limit: 5 }],
    queryFn: async ({ signal }) => {
      const response = await fetch(\`\${apiBase()}/posts?limit=5\`, {
        signal,
        headers: { accept: 'application/json' },
      })
      if (!response.ok) throw new Error(\`HTTP \${response.status}\`)
      const payload = (await response.json()) as {
        items?: Array<{ id?: string; title?: string }>
        total?: number
      }
      const items = (payload.items ?? [])
        .filter((item) => item.id && item.title)
        .map((item) => ({ id: item.id as string, title: item.title as string }))
      const total = typeof payload.total === 'number' ? payload.total : items.length
      return { total, items }
    },
  })

  return (
    <section className="posts" aria-label="Posts from API">
      <p className="eyebrow">Live data</p>
      <h2>Recent posts</h2>
      {isPending ? (
        <p className="muted">Loading posts from the API…</p>
      ) : isError ? (
        <p className="muted">
          {error instanceof Error ? error.message : 'Posts route is not reachable yet'}
        </p>
      ) : data.total === 0 ? (
        <p className="muted">
          No posts yet. Seed the database or POST to <code>/posts</code> with{' '}
          <code>Authorization: Bearer demo</code>.
        </p>
      ) : (
        <>
          <p className="muted">{data.total} post(s) in the database.</p>
          <ul className="post-list">
            {data.items.map((post: PostPreview) => (
              <li key={post.id}>
                <span>{post.title}</span>
                <code>{post.id.slice(0, 8)}…</code>
              </li>
            ))}
          </ul>
        </>
      )}
    </section>
  )
}

export default function HomePage() {
  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">Generated by Arche</p>
        <h1>Your service-backed fullstack base is ready.</h1>
        <p className="lede">
          Next.js on the surface, Axum and SQLx underneath. Health and posts routes are wired on
          this page so you can see the API respond before you add product code.
        </p>
        <div className="actions" aria-label="Local commands">
          <code>bun dev</code>
          <code>cd services/api && cargo run</code>
        </div>
      </section>

      <ApiStatus />
      <PostsPreview />

      <section className="grid" aria-label="Generated services">
        {services.map(([name, detail, target]) => (
          <article key={name} className="card">
            <span>{name}</span>
            <h2>{detail}</h2>
            <p>{target}</p>
          </article>
        ))}
      </section>
    </main>
  )
}
`
}
