/** Premium minimalist homepage for service-API fullstack scaffolds (rust-fullstack, polyglot swaps). */

export function renderServiceApiWebLayout(): string {
  return `import type { Metadata } from 'next'
import './styles.css'

export const metadata: Metadata = {
  title: 'Arche Scaffold',
  description: 'Service-backed fullstack scaffold generated by Arche.',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`
}

export function renderServiceApiWebPage(): string {
  return `'use client'

import { useEffect, useState } from 'react'

const services = [
  ['Web', 'Next.js app router', 'http://localhost:3000'],
  ['API', 'Axum REST + SQLx', 'http://localhost:3001'],
  ['Posts', 'Module-first CRUD', '/posts'],
  ['Runtime', 'Service-owned backend', 'services/api'],
] as const

type ApiState =
  | { status: 'checking'; message: string }
  | { status: 'online'; message: string }
  | { status: 'offline'; message: string }

type PostPreview = { id: string; title: string }

type PostsState =
  | { status: 'checking' }
  | { status: 'online'; total: number; items: PostPreview[] }
  | { status: 'offline'; message: string }
  | { status: 'empty' }

function apiBase(): string {
  return (process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001').replace(/\\/$/, '')
}

function ApiStatus() {
  const [apiState, setApiState] = useState<ApiState>({
    status: 'checking',
    message: 'Checking API health...',
  })

  useEffect(() => {
    const controller = new AbortController()

    fetch(\`\${apiBase()}/health\`, {
      signal: controller.signal,
      headers: { accept: 'application/json' },
    })
      .then(async (response) => {
        if (!response.ok) throw new Error(\`HTTP \${response.status}\`)
        const payload = (await response.json().catch(() => null)) as { status?: string } | null
        setApiState({
          status: 'online',
          message: payload?.status ? \`API says \${payload.status}\` : 'API health route is online',
        })
      })
      .catch((error: unknown) => {
        if (controller.signal.aborted) return
        setApiState({
          status: 'offline',
          message: error instanceof Error ? error.message : 'API is not reachable yet',
        })
      })

    return () => controller.abort()
  }, [])

  return (
    <section className="status" aria-label="Live API status">
      <div>
        <span className={apiState.status === 'online' ? 'dot online' : 'dot'} />
        <p className="eyebrow">Live API check</p>
        <h2>{apiState.message}</h2>
      </div>
      <code>NEXT_PUBLIC_API_URL=http://localhost:3001</code>
    </section>
  )
}

function PostsPreview() {
  const [postsState, setPostsState] = useState<PostsState>({ status: 'checking' })

  useEffect(() => {
    const controller = new AbortController()

    fetch(\`\${apiBase()}/posts?limit=5\`, {
      signal: controller.signal,
      headers: { accept: 'application/json' },
    })
      .then(async (response) => {
        if (!response.ok) throw new Error(\`HTTP \${response.status}\`)
        const payload = (await response.json()) as {
          items?: Array<{ id?: string; title?: string }>
          total?: number
        }
        const items = (payload.items ?? [])
          .filter((item) => item.id && item.title)
          .map((item) => ({ id: item.id as string, title: item.title as string }))
        const total = typeof payload.total === 'number' ? payload.total : items.length
        if (total === 0) {
          setPostsState({ status: 'empty' })
          return
        }
        setPostsState({ status: 'online', total, items })
      })
      .catch((error: unknown) => {
        if (controller.signal.aborted) return
        setPostsState({
          status: 'offline',
          message: error instanceof Error ? error.message : 'Posts route is not reachable yet',
        })
      })

    return () => controller.abort()
  }, [])

  return (
    <section className="posts" aria-label="Posts from API">
      <p className="eyebrow">Live data</p>
      <h2>Recent posts</h2>
      {postsState.status === 'checking' ? (
        <p className="muted">Loading posts from the API…</p>
      ) : postsState.status === 'offline' ? (
        <p className="muted">{postsState.message}</p>
      ) : postsState.status === 'empty' ? (
        <p className="muted">
          No posts yet. Seed the database or POST to <code>/posts</code> with{' '}
          <code>Authorization: Bearer demo</code>.
        </p>
      ) : (
        <>
          <p className="muted">{postsState.total} post(s) in the database.</p>
          <ul className="post-list">
            {postsState.items.map((post) => (
              <li key={post.id}>
                <span>{post.title}</span>
                <code>{post.id.slice(0, 8)}…</code>
              </li>
            ))}
          </ul>
        </>
      )}
    </section>
  )
}

export default function HomePage() {
  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">Generated by Arche</p>
        <h1>Your service-backed fullstack base is ready.</h1>
        <p className="lede">
          Next.js on the surface, Axum and SQLx underneath. Health and posts routes are wired on
          this page so you can see the API respond before you add product code.
        </p>
        <div className="actions" aria-label="Local commands">
          <code>bun dev</code>
          <code>cd services/api && cargo run</code>
        </div>
      </section>

      <ApiStatus />
      <PostsPreview />

      <section className="grid" aria-label="Generated services">
        {services.map(([name, detail, target]) => (
          <article key={name} className="card">
            <span>{name}</span>
            <h2>{detail}</h2>
            <p>{target}</p>
          </article>
        ))}
      </section>
    </main>
  )
}
`
}
