import type { Metadata } from 'next'
import './styles.css'

export const metadata: Metadata = {
  title: 'Arche Scaffold',
  description: 'Next.js scaffold generated by Arche.',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
