const highlights = [
  ['App Router', 'Next.js 16 with a clean starting layout'],
  ['TypeScript', 'Strict defaults and room to grow'],
  ['Deploy-ready', 'Env examples and CI hooks when enabled'],
] as const

export default function HomePage() {
  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">Generated by Arche</p>
        <h1>Your Next.js base is ready.</h1>
        <p className="lede">
          A quiet, production-minded starting point—no filler components, no mystery folders. Add
          routes, data, and design tokens when your product needs them.
        </p>
        <div className="actions" aria-label="Local commands">
          <code>bun dev</code>
          <code>bun run build</code>
        </div>
      </section>

      <section className="grid" aria-label="Scaffold highlights">
        {highlights.map(([name, detail]) => (
          <article key={name} className="card">
            <span>{name}</span>
            <h2>{detail}</h2>
          </article>
        ))}
      </section>
    </main>
  )
}
