import { HighlightCard } from '@/components/highlight-card'

const highlights = [
  ['App Router', 'Next.js 16 with error, loading, and not-found boundaries'],
  ['Env validation', '@t3-oss/env-nextjs keeps public config honest at build time'],
  ['Health route', 'GET /api/health proves Route Handlers without a backend'],
] as const

export default function HomePage() {
  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">Generated by Arche</p>
        <h1>Your Next.js base is ready.</h1>
        <p className="lede">
          A quiet, production-minded starting point with validated env, SEO metadata, design tokens,
          and a sample API route. Add data and auth when your product needs them.
        </p>
        <div className="actions" aria-label="Local commands">
          <code>bun dev</code>
          <code>bun run build</code>
        </div>
      </section>

      <section className="grid" aria-label="Scaffold highlights">
        {highlights.map(([name, detail]) => (
          <HighlightCard key={name} label={name} title={detail} />
        ))}
      </section>
    </main>
  )
}
